

services:
  postgres:
    container_name: postgres-sql-appliance-store
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appliance_store
    ports:
      - "5432:5432"

  appliance-store-app:
    container_name: appliance-store-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-sql-appliance-store:5432/appliance_store
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
     - postgres












